### ISSUE TITLE
nm_extract error creating listmode header

### ISSUE THREAD

**Issue by rijobro** [UCL/pet-rd-tools#34]
For certain files, `nm_extract` works fine, but for some others I've had a problem (although we're not sure if it's `pet-rd-tools` or something else (e.g., `gdcm`). 

In `nmtools/MMR.hpp`, the DICOM tag `(0x029, 0x1010)` is initially used. If the returned string does not contain `SV10`, `(0x029, 0x1110)` is used instead. 

However, for some images, the following line (in `Common.hpp`):
```
inStream << std::fixed << element.GetValue();
```
returns the length of the string instead of the string itself. This then causes problems. 

For these images, we can manually change the code to look straight for `(0x029, 0x1110)`, skipping out `(0x029, 0x1010)` altogether.

Sorry if this message is a bit cryptic, I can probably explain it better in person. @KrisThielemans helped with the debugging.

**Comment by KrisThielemans** [comment]
It actually returns the string `Loaded:XX` with XX the number of bytes.

[This post](https://sourceforge.net/p/gdcm/mailman/message/27848596/) might help.
