### ISSUE TITLE
empty global scanner calibration factor in norm file

### ISSUE THREAD

**Issue by szho42** [UCL/pet-rd-tools#53]
Hi,

After using nm_extract to convert normalization file (Simenes raw data, a dicom header and a binary .bf file), the value of 'GLOBAL SCANNER CALIBRATION FACTOR' in the xxxx.n.hdr file is empty.

Just wondering what could cause this value to be empty?

---- part of the normalization header file ----

**%GLOBAL SCANNER CALIBRATION FACTOR:=**
%scanner quantification factor (Bq*s/ECAT counts):=1.94365e+007
%calibration date (yyyy:mm:dd):=2016:08:10
%calibration time (hh:mm:ss GMT+00:00):=22:55:32
%cross calibration factor:=1.014

Thanks

**Comment by KrisThielemans** [comment]
as `nm_extract` essentially just copies the header from the data (with adjusting the filename), I strongly suspect that it isn't in the DICOM file either. You could check that with e.g. `dcmdump` or indeed just `strings`.

In any case, I believe this is as expected: it seems to be  a "group" keyword (like `!GENERAL DATA:=` et al.). It is also the case with our norm files.
